#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NDK=$(realpath $DIR/../../../../../)
if [ "$1" != "-cc1" ]; then
    $DIR/clang++ --target=aarch64-linux-android21 -I$NDK/sysroot/usr/include/ -I$NDK/sysroot/usr/include/aarch64-linux-android/ -gcc-toolchain $NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-* -L$NDK/platforms/android-21/arch-arm64/usr/lib/ -B$NDK/platforms/android-21/arch-arm64/usr/lib/ -Wno-error=unused-command-line-argument "$@"
else
    # Target is already an argument.
    $DIR/clang++ "$@"
fi
