#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NDK=$(realpath $DIR/../../../../../)
if [ "$1" != "-cc1" ]; then
    $DIR/clang++ --target=armv5-linux-androideabi9 -I$NDK/sysroot/usr/include/ -I$NDK/sysroot/usr/include/arm-linux-androideabi/ -gcc-toolchain $NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-* -L$NDK/platforms/android-14/arch-arm/usr/lib/ -B$NDK/platforms/android-14/arch-arm/usr/lib/ -Wno-error=unused-command-line-argument "$@"
else
    # Target is already an argument.
    $DIR/clang++ "$@"
fi
