#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NDK=$(realpath $DIR/../../../../../)
if [ "$1" != "-cc1" ]; then
    $DIR/clang --target=x86_64-linux-android21 -I$NDK/sysroot/usr/include/ -I$NDK/sysroot/usr/include/x86_64-linux-android/ -gcc-toolchain $NDK/toolchains/x86_64-4.9/prebuilt/linux-* -L$NDK/platforms/android-21/arch-x86_64/usr/lib64/ -B$NDK/platforms/android-21/arch-x86_64/usr/lib64/ -Wno-error=unused-command-line-argument "$@"
else
    # Target is already an argument.
    $DIR/clang "$@"
fi
